services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=production

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=spring-store
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "docker", "-d", "spring-store"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
